#!/bin/bash
#uses cutadapt to remove adapter sequences from reads.
# this is using adapter sequencing hardcoded here and found to be enriched in the VDR dataset

#usage cutadapt -e ERROR-RATE -a ADAPTER-SEQUENCE input.fastq > output.fastq
#e parameter: attention, now you're allowing sequencing error to be detected in the adapter sequence. Correct?

#06/12/12 added other sequences taken from the fastqc list
# these were enriched in the document I sent to Ram etc, together with the truseq adapters
# Illumina Multiplexing PCR Primer 2.01			GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
# Illumina PCR Primer Index 1						CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC
# Illumina PCR Primer Index 2						CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTC
# Illumina PCR Primer Index 3						CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTC
# Illumina PCR Primer Index 4						CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTC
# Illumina PCR Primer Index 5						CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTC
# Illumina PCR Primer Index 6						CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC
# Illumina PCR Primer Index 7						CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTC
# Illumina PCR Primer Index 8						CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTC
# Illumina PCR Primer Index 9						CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTC
# Illumina PCR Primer Index 10					CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTC
# Illumina PCR Primer Index 11					CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTC
# Illumina PCR Primer Index 12					CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTC
# added them at the beginning of the list


if [ ! $# == 1 ]; then
        echo "Usage: `basename $0` <PATH_DATA>"
        echo "PATH_DATA - directory containing the input fastq.gz"
        exit
fi

PDATA=$1;
PCODE="/home/giuseppe/src/pypa-virtualenv-3a798b3/ve/bin";
#my new version of cutadapt is there

for FILE in ${PDATA}/*.fastq.gz;
        do 
        #ID=`echo ${FILE} | egrep -o "GM[0-9]*"`;

	ID=`basename ${FILE} ".fastq.gz"`;
	
	SCRIPT=${ID}.sh;
	echo '#!/bin/bash' >>${PDATA}/${SCRIPT};
        echo '' >>${PDATA}/${SCRIPT};
	echo "${PCODE}/cutadapt -b GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT -b CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTC   -b AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG -b CTTCACCGTGCCAGACTAGAGTCAAGCTCAACAGGGTCTTCTTTCCCCGCTG -b GGATGAACGAGATTCCCACTGTCCCTACCTACTATCCAGCGAAACCACAGCC -b CTCCCTTTCGATCGGCCGAGGGCAACGGAGGCCATCGCCCGTCCCTTCGGAA -b CGAGATTCCCACTGTCCCTACCTACTATCCAGCGAAACCACAGCCAAGGGAA -b CCACTCTCGACTGCCGGCGACGGCCGGGTATGGGCCCGACGCTCCAGCGCCA -b TGGAAGTCGGAATCCGCTAAGGAGTGTGTAACAACTCACCTGCCGAATCAAC -b CCTATACCCAGGTCGGACGACCGATTTGCACGTCAGGACCGCTACGGACCTC -b CACGAGCGCACGTGTTAGGACCCGAAAGATGGTGAACTATGCCTGGGCAGGG -b GTCGGAATCCGCTAAGGAGTGTGTAACAACTCACCTGCCGAATCAACTAGCC -b CTCCCGTCCACTCTCGACTGCCGGCGACGGCCGGGTATGGGCCCGACGCTCC -b CGCAGGTTCAGACATTTGGTGTATGTGCTTGGCTGAGGAGCCAATGGGGCGA -b GAACGAGATTCCCACTGTCCCTACCTACTATCCAGCGAAACCACAGCCAAGG -b CAGAAGGGCAAAAGCTCGCTTGATCTTGATTTTCAGTACGAATACAGACCGT -b TTTCGATCGGCCGAGGGCAACGGAGGCCATCGCCCGTCCCTTCGGAACGGCG -e 0.15 -O 4 -m 20 ${FILE} -o ${PDATA}/${ID}_trimmed.fastq.gz" >>${PDATA}/${SCRIPT};
        nice -5 qsub -e ${PDATA}/${ID}.err -o ${PDATA}/${ID}.out -q medium_jobs.q ${PDATA}/${SCRIPT};
	rm ${PDATA}/${SCRIPT}; 
done
